name: "Outputs in Github Action"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'major.minor.patch'
        required: true
jobs:
  first_job:
    name: Erster Job
    runs-on: ubuntu-latest
    steps:
      - name: First Step from first Job
        id: job_1_step_1
        run: |
          echo "An dieser Stelle nehme ich das Inputfield für die weitere Verwendung als Output"
          echo "Das Inputfield kann via $""{{ github.event.inputs.version }} abgerufen werden und enthält aktuell: ${{ github.event.inputs.version }}"
          echo ""
          echo "Nun schreibe ich den Inhalt von $""{{ github.event.inputs.version }} in die Outputs"
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "In dem Step in welchem in die Outputs definiert wurden können diese nicht abgerufen werden"
          echo "Innerhalb dieses Steps wird $""{{ steps.job_1_step_1.outputs.test }} nicht ausgegeben:"
          echo ${{ steps.job_1_step_1.outputs.test }}
