name: "Variablen innerhalb von Github Actions"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'major.minor.patch'
        required: true
jobs:
  job_1:
    name: "Job Name: ${{ github.event.inputs.version }} by github.event.inputs.version"

    runs-on: ubuntu-latest
    steps:
      - name: Definition und Ausgabe
        id: working_1
        run: |
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          # Direkte Ausgabe
          echo ${{needs.testing.outputs.version}}
          # ist leer
          echo ${{steps.working_1.outputs.version}}


          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          # Direkte Ausgabe
          echo ${{ env.version }}
          # ist leer

          version="${{ github.event.inputs.version }}"
          echo $version
      - name: Ausgabe
        id: working_2
        run: |
          # Wird nicht angezeigt:
          echo ${{needs.testing.outputs.version}}
          # Wird angezeigt
          echo ${{steps.working_1.outputs.version}}
          # Wird angezeigt
          echo ${{ env.version }}
          # Wird nicht angezeigt
          echo $VERSION
      - name: "Step output: ${{steps.working_1.outputs.version}}"
        id: working_3
        run: echo ${{steps.working_1.outputs.version}}
      - name: "ENV: ${{ env.version }}"
        id: working_4
        run: echo ${{ env.version }}
    outputs:
      version: ${{ steps.working_1.outputs.version }}
  testing_1:
    name: asdas
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - env:
        version: ${{needs.job_1.outputs.version}}
        run: echo ${{needs.job_1.outputs.version}}
      - name: "ENV: ${{ env.version }}"
        id: working_4
        run: echo ${{ env.version }}
      - name: "Step output: ${{steps.working_1.outputs.version}}"
        id: working_5
        run: echo ${{steps.working_1.outputs.version}}
      - name: "ENV: ${{ env.version }}"
        id: working_6
        run: echo $version